apiVersion: v1
kind: ConfigMap
metadata:
  name: linkhub-config
  namespace: linkhub
  labels:
    app.kubernetes.io/name: linkhub
data:
  # PostgreSQL
  POSTGRES_DB: "linkhub"
  POSTGRES_USER: "linkhub"

  # Spring profiles
  SPRING_PROFILES_ACTIVE: "prod"

  # Datasource (host will be the k8s service name)
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/linkhub"
  SPRING_DATASOURCE_USERNAME: "linkhub"

  # Redis
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"

  # Kafka
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"

  # Application
  APP_BASE_URL: "https://lnk.hub"
  APP_FRONTEND_URL: "https://lnk.hub"

  # GeoIP
  GEOIP_DATABASE_PATH: "/data/geoip/GeoLite2-City.mmdb"
